_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 2
                - 3
                - 11
                - 41
                - 49
                - 55
            "2":
                - 1
                - 2
                - 3
                - 11
                - 41
                - 49
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.9.20
            "5": 0.18.5
            "6": 4.46.1
            "8":
                - 5
                - 9
            "12": 0.18.5
            "13": linux-x86_64
app:
    value: vjepa
data:
    value:
        batch_size: 24
        clip_duration: null
        crop_size: 224
        dataset_type: VideoDataset
        datasets:
            - /home/madhavan/jepa/data/droid_videos_2/video_labels.csv
        decode_one_clip: true
        eval_datasets:
            - /home/madhavan/jepa/data/droid_videos_2/video_labels_eval.csv
        filter_short_videos: false
        mask_type: multiblock3d
        num_clips: 1
        num_frames: 16
        num_workers: 0
        patch_size: 16
        pin_mem: true
        sampling_rate: 4
        tubelet_size: 2
data_aug:
    value:
        auto_augment: false
        motion_shift: false
        random_resize_aspect_ratio:
            - 0.75
            - 1.35
        random_resize_scale:
            - 0.3
            - 1
        reprob: 0
logging:
    value:
        folder: /home/madhavan/jepa/logging/
        write_tag: debug_stage1
loss:
    value:
        loss_exp: 1
        reg_coeff: 0
mask:
    value:
        - aspect_ratio:
            - 0.75
            - 1.5
          max_keep: null
          max_temporal_keep: 1
          num_blocks: 8
          spatial_scale:
            - 0.15
            - 0.15
          temporal_scale:
            - 1
            - 1
        - aspect_ratio:
            - 0.75
            - 1.5
          max_keep: null
          max_temporal_keep: 1
          num_blocks: 2
          spatial_scale:
            - 0.7
            - 0.7
          temporal_scale:
            - 1
            - 1
meta:
    value:
        dtype: bfloat16
        eval_freq: 100
        load_checkpoint: true
        read_checkpoint: /home/madhavan/jepa/ckpts/vitl16.pth
        seed: 234
        use_sdpa: true
model:
    value:
        action_dim: 1024
        model_name: vit_large
        pred_depth: 12
        pred_embed_dim: 384
        token_learning_model: tokenlearner
        uniform_power: true
        use_mask_tokens: true
        zero_init_mask_tokens: true
nodes:
    value: 1
optimization:
    value:
        clip_grad: 10
        ema:
            - 0.998
            - 1
        epochs: 400
        final_lr: 1e-06
        final_weight_decay: 0.4
        ipe_scale: 1.25
        lr: 0.000625
        start_lr: 0.0002
        warmup: 40
        weight_decay: 0.04
tasks_per_node:
    value: 1
